Update README.md
cryptic-game/cryptic pull request #62
Opened 2021-06-22 18:46 UTC by MarcelCoding

https://discord.com/channels/454739001841025024/454750853967118336/856966453219557426 + followings ...

2021-08-27 13:30 UTC, Tristan-H11 requested changes
Please correct these two typos. @MarcelCoding

2021-08-27 13:30 UTC, Tristan-H11 commented on README.md
> +But you can also play in an virtual terminal: [PyCrypCli](https://github.com/Defelo/PyCrypCli)
```suggestion
But you can also play in a virtual terminal: [PyCrypCli](https://github.com/Defelo/PyCrypCli)
```

2021-08-27 13:30 UTC, Tristan-H11 commented on README.md
>  More clients are everywhere in the internet, so it's your choice.
```suggestion
More clients are everywhere on the internet, so it's your choice.
```

2021-08-27 13:56 UTC, Tristan-H11 commented
@Defelo @DevMimas  Please approve if ok

2021-09-21 19:14 UTC, Defelo submitted a review, later dismissed

2021-09-26 16:52 UTC, DevMimas commented
Please delete the faq@cryptic-game.net is not in use

2021-09-27 08:15 UTC, ClientCrash requested changes
Please add a small text on the bottom that these rule (specifically the no-bots rule) applies only on the official backend and not self hosted ones.

2021-12-11 22:45 UTC, cadamini commented
> Please delete the [faq@cryptic-game.net](mailto:faq@cryptic-game.net) is not in use

This will close https://github.com/cryptic-game/cryptic/issues/50

2021-12-12 05:29 UTC, Tristan-H11 approved these changes

2021-12-12 07:34 UTC, DevMimas approved these changes

2021-12-12 07:38 UTC, Defelo approved these changes

2021-12-12 07:40 UTC, merged