Add DE wiki page with instructions
cryptic-game/cryptic pull request #66
Opened 2021-12-11 22:41 UTC by cadamini

**Description**
Add link to DE wiki page with instruction in readme. 

**Issue**
Closes https://github.com/cryptic-game/cryptic/issues/65 

**Testing Instructions**
not required

2021-12-12 05:36 UTC, Tristan-H11 commented
The wiki page you linked is about how to play the game. Maybe the link would be better off a section lower in "I want to play!" instead of under the question, what the game itself is at all. <3

2021-12-12 14:24 UTC, cadamini commented
@Tristan-H11 Updated texts a bit more and moved the link. Feel free to close this PR if this was too much

2021-12-12 14:39 UTC, Tristan-H11 requested changes
If you don't mind, please implement these changes, so we can merge the PR. :)

2021-12-12 14:39 UTC, Tristan-H11 commented on README.md
> +Cryptic is an deep strategy game. The goal of this deep strategy game is to hack other players and think creative like real hackers. You only start with a virtual computer and a few crypto coins. You
```suggestion
Cryptic is a deep strategy game. The goal of this deep strategy game is to hack other players and think creatively like real hackers. You only start with a virtual computer and a few crypto coins. You must think carefully about your actions before attacking another player and learn the basics of the game. But it's not hard to get started.  
```

2021-12-12 14:39 UTC, Tristan-H11 commented on README.md
> +Cryptic is driven by a not profit-oriented team that maintains the game, adds new features and releases new versions.
```suggestion
Cryptic is driven by a non-profit-oriented team that maintains the game, adds new features, and releases new versions.
```

2021-12-12 15:44 UTC, Tristan-H11 submitted a review, later dismissed

2021-12-12 22:14 UTC, cadamini commented on README.md
> +Refer to our [wiki](https://wiki.cryptic-game.net/books/spielanleitung) (German) for instructions or visit our Youtube channel for Let's Play videos.
```suggestion
Refer to our wiki for [German](https://wiki.cryptic-game.net/books/spielanleitung) or [English](https://wiki.cryptic-game.net/books/game-manual) instructions or visit our Youtube channel for a Let's Play video.
```

2021-12-13 05:33 UTC, Tristan-H11 approved these changes

2021-12-13 16:06 UTC, Defelo approved these changes

2021-12-13 16:07 UTC, merged